apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: bootstrap
spec:
  ports:
    - name: kafka-broker-port
      port: 9092
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-headless
  annotations:
  service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: kafka-port
      port: 9092
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
spec:
  serviceName: kafka-headless
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: liveget/kafka_aarch64:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_HEAP_OPTS
          value: -Xmx2G -Xms2G
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_AUTO_LEADER_REBALANCE_ENABLE
          value: "true"
        command:
            - /bin/sh
            - -exc
            - |
              unset KAFKA_PORT && \
              export KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_SERVICE_HOST}:${KAFKA_ZOOKEEPER_SERVICE_PORT} && \
              export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
              export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092 && \
              exec start-kafka.sh
      imagePullSecrets:
      - name: regcred
