apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: bootstrap
spec:
  ports:
    - name: kafka-broker-port
      port: 9092
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: kafka-port
      port: 9092
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
spec:
  serviceName: kafka-headless
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
      containers:
      - name: kafka
        image: liveget/kafka_aarch64:0.0.2
        imagePullPolicy: Always
        ports:
        - name: inside
          containerPort: 9092
        - name: outside
          containerPort: 9094
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092,OUTSIDE://:9094
        - name: KAFKA_HEAP_OPTS
          value: -Xmx2G -Xms2G
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_AUTO_LEADER_REBALANCE_ENABLE
          value: "true"
        command:
            - /bin/sh
            - -exc
            - |
              unset KAFKA_PORT && \
              export KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_SERVICE_HOST}:${KAFKA_ZOOKEEPER_SERVICE_PORT} && \
              export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
              export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092,OUTSIDE://${POD_IP}:32094 && \
              exec start-kafka.sh
        readinessProbe:
          tcpSocket:
            port: 9092
          timeoutSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /kafka
      volumes:
      - name: data
        emptyDir: {}
      imagePullSecrets:
      - name: regcred
