apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-1
  name: kafka-1
spec:
  ports:
    - name: kafka-1-port
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka-1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-2
  name: kafka-2
spec:
  ports:
    - name: kafka-2-port
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: kafka-2
  type: LoadBalancer
